server:
  applicationConnectors:
    - type: http
      port: ${MARQUEZ_APPLICATION_PORT}
  adminConnectors:
    - type: http
      port: ${MARQUEZ_ADMIN_PORT}

logging:
  level: INFO
  loggers:
    marquez: DEBUG

db:
  driverClass: org.postgresql.Driver
  url: jdbc:postgresql://${MARQUEZ_POSTGRES_HOST}:${MARQUEZ_POSTGRES_PORT}/${MARQUEZ_POSTGRES_DB}
  user: ${MARQUEZ_POSTGRES_USER}
  password: ${MARQUEZ_POSTGRES_PASSWORD}
  maxSize: 10
  minSize: 2
  validationQuery: "SELECT 1"
