worker_processes 1;

events {
  worker_connections 1024;
}

http {
  include       mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;

    location /vector-star/ {
      proxy_pass http://vector-star:8686/;
    }

    location /vector-mdsc/ {
      proxy_pass http://vector-mdsc:8686/;
    }

    location /vector-tech360/ {
      proxy_pass http://vector-tech360:8686/;
    }

    location / {
      return 404;
    }
  }
}
