name: Deploy to ECS (Dev)

on:
  push:
    branches:
      - efs # Trigger only when code is pushed to this branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.x" # Or your preferred version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=redshift-data-migration-bucket" -backend-config="key=grafana/terraform.tfstate" -backend-config="region=us-east-1"

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="terraform.tfvars"
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/grafana-branch' && github.event_name == 'push' && steps.plan.outcome != 'failure'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Output Grafana URL
        if: steps.apply.outcome == 'success'
        run: echo "Grafana URL: $(terraform output -raw grafana_url)"